"""empty message

Revision ID: 13e655ce1ec5
Revises: 303a451bcb1b
Create Date: 2025-12-16 11:05:04.829712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e655ce1ec5'
down_revision: Union[str, Sequence[str], None] = '303a451bcb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Inventories', ['id'])
    op.add_column('Weapons', sa.Column('inventory_id', sa.String(length=4), nullable=True))
    op.drop_constraint(op.f('Weapons_user_id_fkey'), 'Weapons', type_='foreignkey')
    op.create_foreign_key(None, 'Weapons', 'Inventories', ['inventory_id'], ['id'], ondelete='SET NULL')
    op.drop_column('Weapons', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Weapons', sa.Column('user_id', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Weapons', type_='foreignkey')
    op.create_foreign_key(op.f('Weapons_user_id_fkey'), 'Weapons', 'Heroes', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('Weapons', 'inventory_id')
    op.drop_constraint(None, 'Inventories', type_='unique')
    # ### end Alembic commands ###
