"""empty message

Revision ID: 303a451bcb1b
Revises: a07e78c6489c
Create Date: 2025-12-15 14:53:34.055945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303a451bcb1b'
down_revision: Union[str, Sequence[str], None] = 'a07e78c6489c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Weapons_user_id_key'), 'Weapons', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('Weapons_user_id_key'), 'Weapons', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
