"""change to many-to-many

Revision ID: 534e60b52e9f
Revises: 0ce26b23ccd9
Create Date: 2025-12-16 15:28:08.782343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534e60b52e9f'
down_revision: Union[str, Sequence[str], None] = '0ce26b23ccd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Inventory_Weapons', ['id'])
    op.drop_constraint(op.f('Weapons_inventory_id_fkey'), 'Weapons', type_='foreignkey')
    op.drop_column('Weapons', 'inventory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Weapons', sa.Column('inventory_id', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('Weapons_inventory_id_fkey'), 'Weapons', 'Inventories', ['inventory_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'Inventory_Weapons', type_='unique')
    # ### end Alembic commands ###
