"""added timestamps columns

Revision ID: 84cd6d04c7b7
Revises: 13e655ce1ec5
Create Date: 2025-12-16 11:42:53.824963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84cd6d04c7b7'
down_revision: Union[str, Sequence[str], None] = '13e655ce1ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Heroes', sa.Column('added_at', sa.DateTime(), nullable=False))
    op.add_column('Heroes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('Inventories', sa.Column('added_at', sa.DateTime(), nullable=False))
    op.add_column('Inventories', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('Weapons', sa.Column('added_at', sa.DateTime(), nullable=False))
    op.add_column('Weapons', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Weapons', 'updated_at')
    op.drop_column('Weapons', 'added_at')
    op.drop_column('Inventories', 'updated_at')
    op.drop_column('Inventories', 'added_at')
    op.drop_column('Heroes', 'updated_at')
    op.drop_column('Heroes', 'added_at')
    # ### end Alembic commands ###
