"""empty message

Revision ID: a07e78c6489c
Revises: 
Create Date: 2025-12-14 22:41:53.132693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07e78c6489c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Heroes', ['id'])
    op.alter_column('Weapons', 'user_id',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.create_unique_constraint(None, 'Weapons', ['id'])
    op.drop_constraint(op.f('Weapons_user_id_fkey'), 'Weapons', type_='foreignkey')
    op.create_foreign_key(None, 'Weapons', 'Heroes', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Weapons', type_='foreignkey')
    op.create_foreign_key(op.f('Weapons_user_id_fkey'), 'Weapons', 'Heroes', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'Weapons', type_='unique')
    op.alter_column('Weapons', 'user_id',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.drop_constraint(None, 'Heroes', type_='unique')
    # ### end Alembic commands ###
