"""empty message

Revision ID: ca8c926615f2
Revises: cf1a6c798078
Create Date: 2025-12-17 17:22:15.847317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8c926615f2'
down_revision: Union[str, Sequence[str], None] = 'cf1a6c798078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Inventories', sa.Column('hero_id', sa.String(length=4), nullable=False))
    op.drop_constraint(op.f('Inventories_user_id_key'), 'Inventories', type_='unique')
    op.create_unique_constraint(None, 'Inventories', ['hero_id'])
    op.drop_constraint(op.f('Inventories_user_id_fkey'), 'Inventories', type_='foreignkey')
    op.create_foreign_key(None, 'Inventories', 'Heroes', ['hero_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Inventories', 'user_id')
    op.add_column('Inventory_Weapons', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_inventory_weapon', 'Inventory_Weapons', ['inventory_id', 'weapon_id'])
    op.add_column('Weapons', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Weapons', 'stock')
    op.drop_constraint('uq_inventory_weapon', 'Inventory_Weapons', type_='unique')
    op.drop_column('Inventory_Weapons', 'quantity')
    op.add_column('Inventories', sa.Column('user_id', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Inventories', type_='foreignkey')
    op.create_foreign_key(op.f('Inventories_user_id_fkey'), 'Inventories', 'Heroes', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'Inventories', type_='unique')
    op.create_unique_constraint(op.f('Inventories_user_id_key'), 'Inventories', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('Inventories', 'hero_id')
    # ### end Alembic commands ###
