"""empty message

Revision ID: e8b27f78282b
Revises: 74524c4184fe
Create Date: 2025-12-16 15:51:16.163851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b27f78282b'
down_revision: Union[str, Sequence[str], None] = '74524c4184fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Inventory_Weapons_weapon_id_fkey'), 'Inventory_Weapons', type_='foreignkey')
    op.drop_constraint(op.f('Inventory_Weapons_inventory_id_fkey'), 'Inventory_Weapons', type_='foreignkey')
    op.create_foreign_key(None, 'Inventory_Weapons', 'Weapons', ['weapon_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Inventory_Weapons', 'Inventories', ['inventory_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Inventory_Weapons', type_='foreignkey')
    op.drop_constraint(None, 'Inventory_Weapons', type_='foreignkey')
    op.create_foreign_key(op.f('Inventory_Weapons_inventory_id_fkey'), 'Inventory_Weapons', 'Inventories', ['inventory_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('Inventory_Weapons_weapon_id_fkey'), 'Inventory_Weapons', 'Weapons', ['weapon_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
